### ISSUE TITLE
Strong Name for MaxMind.GeoIP from NuGet

### ISSUE THREAD

**Issue by Crayder** [maxmind/geoip-api-csharp2#10]
>CSC : error CS1577: Assembly generation failed -- Referenced assembly 'MaxMind.GeoIP' does not have a strong name

I'm getting that when I want to compile a project with the GeoIP package from NuGet.

**Comment by Crayder** [comment]
Solved with an automatic package signer.

**Comment by oschwald** [comment]
The `MaxMind.GeoIP` package on NuGet was released by a third party. For new development, we recommend `MaxMind.GeoIP2`.

**Comment by Crayder** [comment]
Yeah, `MaxMind.GeoIP2` isn't listed in the VS NuGet Package list.

**Comment by oschwald** [comment]
Weird. It is at https://www.nuget.org/packages/MaxMind.GeoIP2.

**Comment by Crayder** [comment]
Yeah I noticed that, I'll just have to use the console.

**Comment by Crayder** [comment]
PM> Install-Package MaxMind.GeoIP2
	Attempting to resolve dependency 'MaxMind.Db (≥ 1.2.0)'.
	Attempting to resolve dependency 'Newtonsoft.Json (≥ 7.0.1)'.
	Installing 'Newtonsoft.Json 7.0.1'.
	Successfully installed 'Newtonsoft.Json 7.0.1'.
	Installing 'MaxMind.Db 1.2.0'.
	Successfully installed 'MaxMind.Db 1.2.0'.
	Installing 'MaxMind.GeoIP2 2.5.0'.
	Successfully installed 'MaxMind.GeoIP2 2.5.0'.
	Adding 'Newtonsoft.Json 7.0.1' to dotnet.
	Uninstalling 'Newtonsoft.Json 7.0.1'.
	Successfully uninstalled 'Newtonsoft.Json 7.0.1'.
	Install failed. Rolling back...
	Install-Package : Could not install package 'Newtonsoft.Json 7.0.1'. You are trying to install this package into a project that 
	targets 'Native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible wit
	h that framework. For more information, contact the package author.
	At line:1 char:16
	+ Install-Package <<<<  MaxMind.GeoIP2
	    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
	    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by oschwald** [comment]
I am surprised `MaxMind.GeoIP` works. This sounds like [this bug](https://github.com/NuGet/Home/issues/1121) to me.

**Comment by Crayder** [comment]
Well it's not working actually, it won't load the databases or something. So I was hoping GeoIP would work.
