### ISSUE TITLE
Error calling Location class

### ISSUE THREAD

**Issue by OtoNoOto** [maxmind/geoip-api-csharp2#11]
I am successfully using the MaxMind GeoIP Legacy .NET API (https://github.com/maxmind/geoip-api-csharp2) Country Class to retrieve Country code based on IP. I am, however, running into issues trying to use the Location class. Below is my code:

```
try
{
    // capture visitors IP
    string visitorIp = Request.UserHostAddress.ToString();

    string geoIpPath = HttpContext.Current.Server.MapPath("~/App_Data/GeoIP.dat");
    LookupService ls = new LookupService(geoIpPath, LookupService.GEOIP_MEMORY_CACHE);
    //get country of the ip address
    Country c = ls.getCountry(visitorIp);
    string countryCode = c.getCode() != "--" ? c.getCode() : "US";


    // Capture country code as cookie
    if (Request.Cookies["GeoIP"] == null)
    {
        HttpCookie cookie = new HttpCookie("GeoIP", countryCode);
        cookie.Expires = DateTime.Now.AddDays(30);
        Response.Cookies.Add(cookie);
    }

    string geoIpCityPath = HttpContext.Current.Server.MapPath("~/App_Data/GeoLiteCity.dat");
    LookupService lsCity = new LookupService(geoIpCityPath, LookupService.GEOIP_MEMORY_CACHE);
    Location l = ls.getLocation(visitorIp);
    <h1>Postal Code = @l.postalCode.ToString()</h1>


}
catch (Exception e)
{
    <p>@e</p>
}
```

The string countryCode is tracked without error. When I try to use the Location class I get the following error message:

> System.ArgumentOutOfRangeException: Non-negative number required. Parameter name: length at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable) at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length) at LookupService.getLocation(Int64 ipnum) in ~\Models\LookupService.cs:line 582 at LookupService.getLocation(IPAddress addr) in ~\Models\LookupService.cs:line 443 at ASP._Page_Views_Shared__GeoIP_cshtml.Execute() in ~\Views\Shared_GeoIP.cshtml:line 34

**Comment by oschwald** [comment]
Closing as this code has long been deprecated. I would recommend that you use GeoIP2 with https://www.nuget.org/packages/MaxMind.GeoIP2/ instead.
