### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by joekuzma** [maxmind/geoip-api-csharp2#9]
I'm using the latest GeoIPISP.dat file, and downloaded the latest C# library...

When doing this code:

            string ServerPath = HttpContext.Current.Server.MapPath("~");
            string GeoipDBPath = ServerPath + "GeoIPISP.dat";
            LookupService ls = new LookupService(GeoipDBPath, LookupService.GEOIP_MEMORY_CACHE);
            //get country of the ip address
            Country c = ls.getCountry(ipaddr.Value);

I get an error "Index was outside the bounds of the array":

Line 300:            }
Line 301:            else {
Line 302:                return new Country(countryCode[ret], countryName[ret]);
Line 303:            }
Line 304:        }

**Comment by oschwald** [comment]
It appears that you are trying to use `getCountry()` to look up a value in the ISP database. You need to use `getISP()` for this. See our [ISP example](https://github.com/maxmind/geoip-api-csharp2/blob/master/examples/ispExample.cs).
